// Mocks generated by Mockito 5.0.3 from annotations
// in data/test/chars/char_remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:data/operations/chars/char_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [CharService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharService extends _i1.Mock implements _i2.CharService {
  MockCharService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<dynamic>> getChars(int? type) =>
      (super.noSuchMethod(Invocation.method(#getChars, [type]),
          returnValue: Future.value(<dynamic>[])) as _i3.Future<List<dynamic>>);
}
