// Mocks generated by Mockito 5.0.3 from annotations
// in domain/test/books/get_books_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:domain/operations/books/book_business.dart' as _i6;
import 'package:domain/operations/books/book_failure.dart' as _i5;
import 'package:domain/operations/books/book_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i3.BookRepository {
  MockBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.BookFailure, List<_i6.BookBusiness>>> getBooks(
          int? type) =>
      (super.noSuchMethod(Invocation.method(#getBooks, [type]),
              returnValue: Future.value(
                  _FakeEither<_i5.BookFailure, List<_i6.BookBusiness>>()))
          as _i4.Future<_i2.Either<_i5.BookFailure, List<_i6.BookBusiness>>>);
}
