// Mocks generated by Mockito 5.0.3 from annotations
// in domain/test/houses/get_houses_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:domain/operations/houses/house_business.dart' as _i6;
import 'package:domain/operations/houses/house_failure.dart' as _i5;
import 'package:domain/operations/houses/house_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [HouseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHouseRepository extends _i1.Mock implements _i3.HouseRepository {
  MockHouseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.HouseFailure, List<_i6.HouseBusiness>>> getHouses(
          int? type) =>
      (super.noSuchMethod(Invocation.method(#getHouses, [type]),
              returnValue: Future.value(
                  _FakeEither<_i5.HouseFailure, List<_i6.HouseBusiness>>()))
          as _i4.Future<_i2.Either<_i5.HouseFailure, List<_i6.HouseBusiness>>>);
}
