// Mocks generated by Mockito 5.0.3 from annotations
// in data/test/books/book_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:common_flutter/network_manager.dart' as _i7;
import 'package:connectivity/connectivity.dart' as _i3;
import 'package:data/operations/books/book_remote_data_source.dart' as _i4;
import 'package:data/operations/books/book_response.dart' as _i6;
import 'package:data/operations/books/book_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeBookService extends _i1.Fake implements _i2.BookService {}

class _FakeConnectivity extends _i1.Fake implements _i3.Connectivity {}

/// A class which mocks [BookRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRemoteDataSource extends _i1.Mock
    implements _i4.BookRemoteDataSource {
  MockBookRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BookService get bookService =>
      (super.noSuchMethod(Invocation.getter(#bookService),
          returnValue: _FakeBookService()) as _i2.BookService);
  @override
  set bookService(_i2.BookService? _bookService) =>
      super.noSuchMethod(Invocation.setter(#bookService, _bookService),
          returnValueForMissingStub: null);
  @override
  _i5.Future<List<_i6.BookResponse>> getBooks(int? type) =>
      (super.noSuchMethod(Invocation.method(#getBooks, [type]),
              returnValue: Future.value(<_i6.BookResponse>[]))
          as _i5.Future<List<_i6.BookResponse>>);
}

/// A class which mocks [NetworkManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkManager extends _i1.Mock implements _i7.NetworkManager {
  MockNetworkManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Connectivity get connectivity =>
      (super.noSuchMethod(Invocation.getter(#connectivity),
          returnValue: _FakeConnectivity()) as _i3.Connectivity);
  @override
  set connectivity(_i3.Connectivity? _connectivity) =>
      super.noSuchMethod(Invocation.setter(#connectivity, _connectivity),
          returnValueForMissingStub: null);
  @override
  _i5.Future<bool> get hasInternetConnection =>
      (super.noSuchMethod(Invocation.getter(#hasInternetConnection),
          returnValue: Future.value(false)) as _i5.Future<bool>);
}
