// Mocks generated by Mockito 5.0.3 from annotations
// in data/test/books/book_remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:data/operations/books/book_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [BookService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookService extends _i1.Mock implements _i2.BookService {
  MockBookService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<dynamic>> getBooks(int? type) =>
      (super.noSuchMethod(Invocation.method(#getBooks, [type]),
          returnValue: Future.value(<dynamic>[])) as _i3.Future<List<dynamic>>);
}
